### ISSUE TITLE
Priority not working?

### ISSUE THREAD

**Issue by thomporter** [ajacksified/Mediator.js#15]
I've got a Chaplin app I'm working on, and I'm having issues using the priority on subscriptions.... Here's a little code:

```
// from my "LayoutView":
mediator.subscribe('log:toggle', this.sizeViews, { priority: 9 });

// from my "LogView":
mediator.subscribe('log:toggle', this.toggleMe, { priority: 1 });
```

I have a `console.log()` in both handlers, and no matter what, the one from my Layout view is called first... I tried it at priority 0, 2 and 9... I want the one from LeftSidebar to fire first...

What am I doing wrong?

I may end up just adding a publish to the `LogView` stating when it's done, and the subscribe to that in my `LayoutView`, but that feels like the easy way out. =)

**Comment by pedroetb** [comment]
I also believe that the priority property is useless this way. It would be better to not modify priority defined by user.
