### ISSUE TITLE
Can I pass a "context" parameter as third argument of "subscribe" function? 

### ISSUE THREAD

**Issue by Elergy** [ajacksified/Mediator.js#20]
A lot of functions which create an event listener allows us pass thisArg as third parameter.
IMHO current third parameter (options) is used not as frequently as thisArg. 
I don't want to impose the opinion, but I really want to have this feature :-)

**Comment by blindfish3** [comment]
Apologies for the necromancy; but to anyone finding this _open_ issue: note that it is now resolved since the `mediator.subscribe` method accepts a `context` parameter. You can pass `null` if you don't want to set any options in the third argument.
