### ISSUE TITLE
bowerInstall - mediator-js was not injected in your file

### ISSUE THREAD

**Issue by KK-MarcelJahn** [ajacksified/Mediator.js#22]
Hi there,

I am using your mighty Mediator in one of my projects.
It's an Angular project generated with yeoman.
I am using bower for all my dependencies and added mediator-js (v.0.9.6) in my bower.json.

When running grunt bowerInstall i get the following error:

"mediator-js was not injected in your file"

The detector looks for mediator-js.js in dependencies root folder but can not find it. (It simply does not exist)

Can you please have a look at this?

Thank you!

**Comment by andrei-cacio** [comment]
:+1: it is because the `bower.json` file is missing

**Comment by andrei-cacio** [comment]
I can make a PR for this
