### ISSUE TITLE
Don't overwrite constructor

### ISSUE THREAD

**Issue by dalgard** [ajacksified/Mediator.js#40]
Thanks for a great library.

I'm using it in a bit of a convoluted way and I'd like to have access to the `Mediator` constructor via the instances' prototype – would you consider either not doing `Mediator.prototype = {...}` or doing a reassignment afterwards?

Like this: `Mediator.prototype.constructor = Mediator`

**Comment by ajacksified** [comment]
https://github.com/ajacksified/Mediator.js/commit/6b4e43431735d74480ec32154777a9071a1c3193
