### ISSUE TITLE
Consider supporting Meteor package format

### ISSUE THREAD

**Issue by dalgard** [ajacksified/Mediator.js#41]
In Meteor, packages are exported by assigning to a global (by omitting the `var` keyword)*.

Please consider adding it at the top of your library. That way, it wouldn't need to be repackaged for Meteor each time you release a new version.

The [standard method](http://www.meteorpedia.com/read/Packaging_existing_Libraries) looks like this:

```javascript
if (typeof Package !== 'undefined') {
  // Meteor
  Mediator = factory();
} else if (typeof define === 'function' && define.amd) {
  // AMD
  define('mediator-js', [], function() {
    global.Mediator = factory();
    return global.Mediator;
  });
} else if (typeof exports !== 'undefined') {
  // Node/CommonJS
  exports.Mediator = factory();
} else {
  // Browser global
  global.Mediator = factory();
}
```

The `Package` check *must* go on top to prevent the Node style export further down.

Thanks for considering this.

(\* Behind the scenes, Meteor creates the variable in a private scope, wraps the library code in an IIFE, and finally exports the var through its own means)

**Comment by ajacksified** [comment]
Feel free to submit a PR!
