### ISSUE TITLE
Channels are not called recursively if the first one is not matched

### ISSUE THREAD

**Issue by BloodyStupidViktor** [ajacksified/Mediator.js#47]
If I listen to 'x:y' and I emit to 'x:y:z', my listener won't trigger. However, if I add a listener for 'x:y:z', then both will trigger. Is this intended? I would expect all 'parent' channels to be visited always, regardless of any gaps in the listeners.
What is the purpose of the namespace check in Mediator.publish? It seems to be the cause.

Best regards

**Comment by majkel89** [comment]
Does not work for me too.
Version 0.9.6 seems to be fine.

**Comment by karol-f** [comment]
+1

**Comment by BloodyStupidViktor** [comment]
Oh, never thought it might work that way. I even find this behavior a bit strange. 'chat:message:received' is a specific 'chat:message' event and triggering it from any 'chat:message' just seems wrong. I'd expect it to be the other way around.

**Comment by pedroetb** [comment]
PR send to apply the change commented by @karol-f 

About that comment inside the source, I think it's not correct. The publication doesn't propagate from top to bottom, even with that "readOnly" flag set to true. It makes no sense, it works just the opposite way (from bottom to top).

**Comment by nlaplume** [comment]
:+1:

**Comment by ajacksified** [comment]
PR merged
