### ISSUE TITLE
Question: constructor style

### ISSUE THREAD

**Issue by adminfyy** [ajacksified/Mediator.js#50]
What does this for ? i dont understand 
can you explain it to me?
inside the Subscriber function : 
`
 if (!(this instanceof Subscriber)) {
      return new Subscriber(fn, options, context);
 }
`

**Comment by ajacksified** [comment]
It abstracts away whether you're using it as a constructor or a function, so these are the same:

```javascript
var mediator = Mediator();
var mediator = new Mediator();
```
