### ISSUE TITLE
Default registration with module "mediator-js" causing problem with requirejs

### ISSUE THREAD

**Issue by digicos** [ajacksified/Mediator.js#51]
I am using require-js to load mediator.js as a dependency. When I register using any name in requirejs config, the module does not load as it gets referenced with a default name "mediator-js" as can be seen in the mediator.js source. 
Can this default behavior be removed ?, so that we may reference it using any other name other than "mediator-js" , I was trying to use "mediatorjs" instead in my requirejs config.

requirejs config
requirejs.config({
    baseUrl: './assets/js/',
    paths: {
        "jquery": 'jquery-1.12.4.min',
        "jqueryui": 'jquery-ui.min',
        "jquerylayout":'jquery.layout-1.4.0',
        **"mediator-js"**:'mediator/mediator' // trying to use "mediatorjs" does not link it to the module.
    }
});

**Comment by ajacksified** [comment]
Pushed as v0.10.0. Let me know if it works, I only use commonjs requires rather than AMD.
