### ISSUE TITLE
Using Mediator with React ?

### ISSUE THREAD

**Issue by agougousis** [ajacksified/Mediator.js#53]
Hi! Is there any way to use this with React ? 

I am new to React so I am not sure how to make it available "globally" so that unrelated React components can communicate between them.

**Comment by ajacksified** [comment]
With React, you're probably better off looking at something like [Redux](https://github.com/reactjs/react-redux) - it's more complicated, but more suited to React (and widely used.)

**Comment by agougousis** [comment]
Thanks for the reply! I have already found my way, though. I've used React's Context. It's simple and works like a charm. Now all of my React components (and even the non-React ones) can communicate between each other using the mediator. So, no unnecessary complexity from Redux. :-)

**Comment by ajacksified** [comment]
Nice! context is a great way to do it simply as well.
