### ISSUE TITLE
requirejs not working, undefined after define call in other modules

### ISSUE THREAD

**Issue by bnewtonius** [ajacksified/Mediator.js#7]
I am trying to use this (v 0.9.0) with requirejs v 2.1.2, and ran into the following issue.  When loading mediator like so:

``` javascript
define(['mediator'], function(Mediator) {
  console.log(Mediator);
});
```

Mediator is undefined.  Looking at the amd section, I noticed it was done differently than some other modules I'm using (mustache to be exact).  I changed mediator to call requirejs properly.  Here's a diff:

``` bash
22c22
<   } else if(typeof root.define === 'function' && root.define.amd) {

---
>   } else if(typeof define === 'function' && define.amd) {
24,27c24
<     root.define([], function() {
<       // Export to global too, for backward compatiblity
<       root.Mediator = factory();
<     });

---
>     define(factory());
```

New code looks like this:

``` javascript
  } else if(typeof define === 'function' && define.amd) {
    // AMD
    define(factory());
  }
```

I'm now getting the Mediator object properly.  I'm not sure if you still need to check "root.define" and "root.define.amd", but the define function should be global at this point anyways if require is there.  I've tested it with this:

``` javascript
  } else if(typeof root.define === 'function' && root.define.amd) {
    // AMD
    root.define(factory());
  }
```

and it worked fine as well.  I think the problem is either (or both) calling define with two arguments, the first being an empty array, and also not returning the pointer to the factory function itself as the second argument.

Can't wait to give your module a try now that I've got it loading.

**EDIT**  Changed the define(factory) calls to define(factory()), since the return is a function to execute on define.

**Comment by akhilagrawal186** [comment]
I am using AngularAMD to include RequireJs in AngularJs. But getting error that "define" is not defined. I defined all dependencies in main.js. Can you please tell me why this error come.

**Comment by bnewtonius** [comment]
I have no idea @akhilagrawal186. My best guess is that you've not added require.js to the webpage prior to using AngularAMD to pull in modules. This doesn't sound like a mediator question though.
